# Generated by Django 3.0.6 on 2020-05-28 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('num', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('book_number', models.CharField(max_length=100)),
                ('status_flag', models.CharField(max_length=1)),
                ('result_flag', models.CharField(max_length=1)),
                ('descriptions', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_by', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultDetails',
            fields=[
                ('resultdetails_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specifications', models.CharField(max_length=100)),
                ('result_flag', models.CharField(max_length=1)),
                ('remark', models.CharField(max_length=100)),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_second_app.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('province', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=1)),
                ('size', models.CharField(max_length=100)),
                ('status_flag', models.CharField(max_length=1)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('files_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=100)),
                ('path', models.FileField(upload_to='')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_second_app.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Assettype',
            fields=[
                ('assettype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('status_flag', models.CharField(max_length=1)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('expire_date', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('assettype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_second_app.Assettype')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_second_app.Location')),
                ('update_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
