# Generated by Django 3.0.4 on 2020-03-30 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.CharField(default=datetime.date.today, max_length=200),
            preserve_default=False,
        ),
    ]
