# Generated by Django 3.0.4 on 2020-04-02 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_result_book_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='create_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='create_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='last_update',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 8, 32, 34, 272550, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='last_update_by',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 8, 32, 43, 207666, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
