# Generated by Django 3.0.4 on 2020-04-16 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200402_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
