# Generated by Django 3.0.4 on 2020-04-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20200416_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdetails',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blogs.Result'),
        ),
    ]
