# Generated by Django 3.0.4 on 2020-04-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200416_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
