# Generated by Django 3.0.4 on 2020-04-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200416_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='last_update_by',
            new_name='update_by',
        ),
    ]
