# Generated by Django 3.0.4 on 2020-04-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20200416_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='resultdetails',
            old_name='Result',
            new_name='result',
        ),
        migrations.AlterField(
            model_name='resultdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
