# Generated by Django 3.0.4 on 2020-04-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200416_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='desc',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='result',
            new_name='result_flag',
        ),
        migrations.RenameField(
            model_name='resultdetails',
            old_name='result',
            new_name='result_flag',
        ),
        migrations.RemoveField(
            model_name='resultdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='resultdetails',
            name='result_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blogs.Result'),
            preserve_default=False,
        ),
    ]
