# Generated by Django 3.0.4 on 2020-04-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200416_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultdetails',
            old_name='result_id',
            new_name='result_uuid',
        ),
    ]
