# Generated by Django 3.0.4 on 2020-04-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20200416_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdetails',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultdetails',
            name='result_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Result'),
        ),
    ]
