# Generated by Django 3.0.4 on 2020-04-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20200416_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultDetails',
        ),
    ]
