# Generated by Django 3.0.4 on 2020-04-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_resultdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultDetails',
        ),
    ]
