# Generated by Django 3.0.4 on 2020-04-22 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_remove_result_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('status_flag', models.CharField(max_length=1)),
                ('update_by', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
