# Generated by Django 3.0.4 on 2020-04-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20200422_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.IntegerField(),
        ),
    ]
