# Generated by Django 3.0.4 on 2020-04-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_auto_20200422_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
