# Generated by Django 3.0.4 on 2020-04-23 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='status_flag',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FileField(upload_to='')),
                ('result_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Result')),
            ],
        ),
    ]
