# Generated by Django 3.0.4 on 2020-04-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0033_auto_20200423_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
