# Generated by Django 3.0.4 on 2020-04-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_auto_20200423_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='name',
            new_name='office_name',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='number',
            new_name='office_number',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='province',
            new_name='office_province',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='size',
            new_name='office_size',
        ),
        migrations.AddField(
            model_name='office',
            name='office_type',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
