# Generated by Django 3.0.4 on 2020-04-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_auto_20200428_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
