# Generated by Django 3.0.4 on 2020-04-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='uuid',
            new_name='office_id',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_province',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_type',
            new_name='status_flags',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='status_flag',
            new_name='type',
        ),
    ]
