# Generated by Django 3.0.4 on 2020-04-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_auto_20200430_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
