# Generated by Django 3.0.4 on 2020-04-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0041_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='uuid',
            new_name='files_id',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='result_uuid',
            new_name='result_id',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='book_number',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='uuid',
            new_name='result_id',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='type_office',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='result',
            name='book_files',
        ),
    ]
