# Generated by Django 3.0.4 on 2020-04-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0042_auto_20200430_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultdetails',
            old_name='uuid',
            new_name='resultdetails_id',
        ),
    ]
