# Generated by Django 3.0.4 on 2020-04-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0043_auto_20200430_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultdetails',
            old_name='result_uuid',
            new_name='result_id',
        ),
    ]
