# Generated by Django 3.0.4 on 2020-04-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0044_auto_20200430_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='book',
            new_name='book_number',
        ),
    ]
