# Generated by Django 3.0.4 on 2020-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='unit',
        ),
        migrations.AddField(
            model_name='assettype',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettype',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettype',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettype',
            name='unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
