# Generated by Django 3.0.4 on 2020-05-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_auto_20200507_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='update_by',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Assettype',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
