# Generated by Django 3.0.4 on 2020-05-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0050_auto_20200507_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assettype',
            fields=[
                ('assettype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('status_flag', models.CharField(max_length=1)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('expire_date', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('assettype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Assettype')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Location')),
                ('update_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
