# Generated by Django 3.0.4 on 2020-05-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0051_asset_assettype_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdetails',
            name='remark',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
