# Generated by Django 3.0.4 on 2020-05-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_resultdetails_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='name',
            new_name='size',
        ),
    ]
